[package]
name = "askama_parser"
version = "0.3.1"
description = "Parser for Askama templates"
documentation = "https://docs.rs/askama"
keywords = ["markup", "template", "jinja2", "html"]
categories = ["template-engine"]
homepage = "https://github.com/djc/askama"
repository = "https://github.com/djc/askama"
license = "MIT OR Apache-2.0"
workspace = ".."
readme = "README.md"
edition = "2021"
rust-version = "1.65"

[dependencies]
nom = { version = "8", default-features = false, features = ["alloc"] }

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "from_str"
harness = false
